title: Aspen Koreny
description: Backend-focused developer specializing in scalable data systems, secure architecture, and performance-driven design.
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
